"""
scripts/export_docx_to_txt.py
------------------------------
One-off, TABLE-AWARE export of the docs/ wireframes to chatbot_docs/*.txt.

Why this exists: the chatbot_docs/*.txt files were generated by a plain
paragraph export that silently DROPS every native Word TABLE. Catalogue /
threat-model / decision-matrix content lives in those tables (e.g. the T-01..T-12
threat model in Architecture §15 and the RT-001..RT-036 red-team catalog in
Guardrail §17.2), so grepping the .txt without them yields "empty headings"
and false "blocked" conclusions. This export flattens tables to pipe-separated
rows (the same convention scripts/seed_knowledge_base.py uses for RAG ingestion),
so the .txt exports carry the same content the docx does.

Usage:
    python -m scripts.export_docx_to_txt [--docs-dir ../docs] [--out-dir ../chatbot_docs]
"""

import argparse
from pathlib import Path

import docx
from docx.oxml.ns import qn
from docx.table import Table
from docx.text.paragraph import Paragraph


def _is_heading(paragraph: Paragraph) -> bool:
    style = (paragraph.style.name if paragraph.style is not None else "") or ""
    lower = style.lower()
    return lower.startswith("heading") or lower == "title"


def _table_to_lines(table: Table) -> list[str]:
    rows: list[str] = []
    n_rows, n_cols = len(table.rows), len(table.columns)
    for row in table.rows:
        cells = [" ".join((cell.text or "").split()) for cell in row.cells]
        line = " | ".join(cells).strip(" |")
        if line.replace("|", "").strip():
            rows.append(line)
    if not rows:
        return []
    return [f"[TABLE: {n_rows} rows x {n_cols} cols]"] + rows + ["[END TABLE]"]


def export_docx(path: Path) -> str:
    d = docx.Document(str(path))
    lines: list[str] = []
    for child in d.element.body.iterchildren():
        if child.tag == qn("w:p"):
            para = Paragraph(child, d)
            text = " ".join((para.text or "").split())
            if text:
                lines.append(text)
        elif child.tag == qn("w:tbl"):
            lines.extend(_table_to_lines(Table(child, d)))
    return "\n".join(lines) + "\n"


def main() -> None:
    here = Path(__file__).resolve().parent.parent  # backend/
    parser = argparse.ArgumentParser(description="Table-aware docx -> txt wireframe export.")
    parser.add_argument("--docs-dir", default=str(here.parent / "docs"))
    parser.add_argument("--out-dir", default=str(here / "chatbot_docs"))
    args = parser.parse_args()

    docs_dir = Path(args.docs_dir)
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    files = sorted(p for p in docs_dir.glob("*.docx") if not p.name.startswith("~$"))
    for path in files:
        text = export_docx(path)
        out_path = out_dir / f"{path.stem}.txt"
        out_path.write_text(text, encoding="utf-8")
        n_tables = text.count("[TABLE:")
        print(f"{path.name}: {len(text.splitlines())} lines, {n_tables} table(s) -> {out_path.name}")


if __name__ == "__main__":
    main()