"""
Regression tests for the customer import preview file-type handling.

Previously, any file with a `.xls` extension (legacy Excel OLE2/CFB, which
openpyxl cannot read) — or any ZIP-prefixed file that is not a valid .xlsx
workbook — was fed to openpyxl and blew up with the cryptic
`BadZipFile: File is not a zip file`. The preview route then translated that
into a generic 500 ("Import preview failed"), so the user could not import.

File dispatch is now content-based (`_detect_and_parse`): a legacy `.xls`
raises a clear, actionable ValueError (422), a corrupt `.xlsx` raises a clear
ValueError, and plain-text/CSV still parses — regardless of extension.

Uses the shared in-memory SQLite fixtures (tests/conftest.py).
"""
import pytest

from app.modules.billing.services.customer_import_service import (
    CustomerImportService,
)
from tests.conftest import make_organization

CSV_BYTES = (
    "Company Name *,Customer Code,Email,Customer Type,Status,Currency,Payment Terms\n"
    "Acme Corp,ACM-001,acme@example.com,business,active,USD,net_30\n"
).encode("utf-8")

LEGACY_XLS_MAGIC = b"\xd0\xcf\x11\xe0\xa1\xb1\x1a\xe1"  # OLE2/CFB header


@pytest.fixture()
def org(db_session):
    return make_organization(db_session)


@pytest.fixture()
def service(db_session):
    return CustomerImportService(db_session)


def _preview(service, org, data, filename):
    return service.preview_import(
        file_bytes=data,
        filename=filename,
        column_map={},
        organization_id=org.id,
        duplicate_strategy="skip",
    )


def test_valid_csv_preview_and_confirm(db_session, service, org):
    res = _preview(service, org, CSV_BYTES, "customers.csv")
    assert res["total"] == 1
    assert res["valid"] == 1
    assert res["invalid"] == 0

    conf = service.confirm_import(
        session_id=res["session_id"],
        organization_id=org.id,
        user_id=1,
        duplicate_strategy="skip",
    )
    assert conf["imported"] == 1
    assert conf["failed"] == 0


def test_legacy_xls_gives_clear_error_not_badzip(service, org):
    # A real legacy .xls (or any file carrying the OLE2 magic header) must
    # raise a readable ValueError, not a cryptic BadZipFile/500.
    with pytest.raises(ValueError) as exc:
        _preview(service, org, LEGACY_XLS_MAGIC + b"fake-xls-bytes", "old.xls")
    assert "xls" in str(exc.value).lower()
    assert "xlsx" in str(exc.value).lower()


def test_corrupt_xlsx_gives_clear_error(service, org):
    # A file that starts with a ZIP header but is not a real workbook would
    # previously surface openpyxl's BadZipFile as a 500.
    with pytest.raises(ValueError) as exc:
        _preview(service, org, b"PK\x03\x04garbage-not-a-workbook", "bad.xlsx")
    assert "xlsx" in str(exc.value).lower()


def test_parse_file_also_rejects_legacy_xls(service, org):
    # parse_file (step 1 of the wizard) must use the same content-based
    # dispatch as preview_import and reject legacy .xls with a clear error.
    with pytest.raises(ValueError) as exc:
        service.parse_file(
            file_bytes=LEGACY_XLS_MAGIC + b"fake-xls-bytes",
            filename="old.xls",
        )
    assert "xls" in str(exc.value).lower()


def test_xls_ext_but_csv_content_is_parsed(service, org):
    # Plain-text CSV content should be parsed as CSV even if named .xls,
    # rather than routed to openpyxl and crashing.
    res = _preview(service, org, CSV_BYTES, "mislabeled.xls")
    assert res["total"] == 1
    assert res["valid"] == 1


def test_autogenerated_code_row_is_valid_not_warning(service, org):
    # A valid row that relies on defaults (no Customer Code, no type/currency/
    # terms) must be counted as VALID, not WARNING. Routine defaults (code
    # auto-generation, defaulted type/currency/terms) are normal behavior and
    # previously mislabeled otherwise-perfect rows, so the whole preview looked
    # broken ("warning") when the import would actually succeed.
    data = ("Company Name *\nAcme Corp\n").encode("utf-8")
    res = _preview(service, org, data, "customers.csv")
    assert res["total"] == 1
    assert res["valid"] == 1
    assert res["warning"] == 0
    assert res["invalid"] == 0

    conf = service.confirm_import(
        session_id=res["session_id"],
        organization_id=org.id,
        user_id=1,
        duplicate_strategy="skip",
    )
    assert conf["imported"] == 1
    assert conf["failed"] == 0


def test_invalid_gstin_still_caught(service, org):
    # A genuinely malformed GSTIN must still reject the row (the template
    # example was fixed to stop shipping 'GSTIN1234', but the validation itself
    # must keep working).
    data = (
        "Company Name *,GST Number\nAcme Corp,GSTIN1234\n"
    ).encode("utf-8")
    res = _preview(service, org, data, "customers.csv")
    assert res["invalid"] == 1
    assert res["valid"] == 0
    assert "GST" in res["rows"][0]["errors"][0]
