"""
migrations/add_platform_invoice_public_token_column.py
---------------------------------------------------------
Idempotent, additive-only migration that adds the
`platform_invoices.public_token` column on EXISTING databases (PostgreSQL or
the dev SQLite fallback).

Fresh databases receive the column automatically from
Base.metadata.create_all. This script exists only because create_all does
NOT alter existing databases — see migrations/create_all/README.md
("Schema changes").

This mirrors `commercial_quotes.public_token`: a signed, per-invoice token
that lets the org view/pay a PlatformInvoice with no login, generated by
PlatformInvoiceService.send() on first send.

Safe to run any number of times:
  - only adds the column when it is missing
  - never drops anything, never deletes data, never alters existing columns

Usage:
    python -m migrations.add_platform_invoice_public_token_column            # apply
    python -m migrations.add_platform_invoice_public_token_column --check    # report only

NOT executed automatically and NOT run against Neon here — run it manually
(once approved) from backend/ with BILLING_DATABASE_URL set:
    set BILLING_DATABASE_URL=postgresql://...
    python -m migrations.add_platform_invoice_public_token_column
"""

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from sqlalchemy import inspect, text  # type: ignore[import]

from app.database import engine

TABLE_NAME = "platform_invoices"
COLUMN_NAME = "public_token"


def _column_exists() -> bool:
    inspector = inspect(engine)
    if not inspector.has_table(TABLE_NAME):
        return False
    return any(col["name"] == COLUMN_NAME for col in inspector.get_columns(TABLE_NAME))


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Add platform_invoices.public_token (idempotent, additive).",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Only report whether the column exists; do not change the database.",
    )
    args = parser.parse_args()

    if args.check:
        print(
            f"Column '{TABLE_NAME}.{COLUMN_NAME}' is "
            f"{'present' if _column_exists() else 'MISSING'}."
        )
        return

    if _column_exists():
        print(f"Column {TABLE_NAME}.{COLUMN_NAME} already exists.")
        return

    with engine.begin() as conn:
        conn.execute(text(f"ALTER TABLE {TABLE_NAME} ADD COLUMN {COLUMN_NAME} VARCHAR(64)"))
        conn.execute(
            text(
                f"CREATE UNIQUE INDEX IF NOT EXISTS ix_{TABLE_NAME}_{COLUMN_NAME} "
                f"ON {TABLE_NAME} ({COLUMN_NAME})"
            )
        )
    print(f"Added column {TABLE_NAME}.{COLUMN_NAME}.")


if __name__ == "__main__":
    main()
