from logging.config import fileConfig

from sqlalchemy import engine_from_config
from sqlalchemy import pool

from alembic import context

# this is the Alembic Config object, which provides
# access to the values within the .ini file in use.
config = context.config

# Interpret the config file for Python logging.
# This line sets up loggers basically.
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Import the application's own SQLAlchemy Base/engine bootstrap. This module
# already imports every model module (auth, organizations, super_admin,
# commercial, billing, chatbot) at its own bottom, so importing it here is
# enough to fully populate Base.metadata before Alembic inspects it — no
# model definitions are duplicated.
#
# resolve_database_url() is the same helper app/database.py uses to build the
# live app's engine (BILLING_DATABASE_URL, +psycopg dialect fix-up, SQLite
# dev fallback), so `alembic` always targets the exact same database the
# FastAPI app would connect to, driven by the same backend/.env.
from app.database import Base, resolve_database_url  # noqa: E402

target_metadata = Base.metadata

config.set_main_option("sqlalchemy.url", resolve_database_url())


def render_item(type_, obj, autogen_context):
    """Correctly render app.core.db_types.CaseInsensitiveEnum in autogenerated code.

    It's a TypeDecorator whose constructor takes a required `enum_class`
    positional argument (see app/core/db_types.py). Alembic's default type
    renderer has no way to know about that argument and emits a bare
    `CaseInsensitiveEnum()` call, which raises TypeError at migration
    runtime (missing enum_class). `obj` here is the live column type
    instance pulled from Base.metadata, so `obj.enum_class` is already the
    real Python enum used by the model — render both it and the enum
    module as explicit imports so the generated file is self-contained.
    """
    if type_ == "type" and type(obj).__name__ == "CaseInsensitiveEnum":
        enum_cls = obj.enum_class
        autogen_context.imports.add("import app.core.db_types")
        autogen_context.imports.add(f"import {enum_cls.__module__}")
        return f"app.core.db_types.CaseInsensitiveEnum({enum_cls.__module__}.{enum_cls.__name__})"
    return False


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode.

    This configures the context with just a URL
    and not an Engine, though an Engine is acceptable
    here as well.  By skipping the Engine creation
    we don't even need a DBAPI to be available.

    Calls to context.execute() here emit the given string to the
    script output.

    """
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        render_item=render_item,
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode.

    In this scenario we need to create an Engine
    and associate a connection with the context.

    """
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            render_item=render_item,
        )

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
