"""add email foundation tables (suppressions, consents, org preferences, audit logs)

Revision ID: 73e2ebbe6aad
Revises: 7709ed1aee3e
Create Date: 2026-09-19 18:35:03.910214

Hand-trimmed from --autogenerate output: the four tables below
(app/services/email_foundation/models.py) have been registered on
Base.metadata since that module was added, but no prior revision ever
created them on Postgres -- confirmed by running
_verify_postgres_schema_is_migrated() against a freshly `alembic upgrade
head`-ed database, which reported exactly these 4 tables missing, and by
reproducing a real UndefinedTable error from
ConsentSuppressionEngine/CommunicationAuditLogger (used by every
send_approval_email() call) against that same database. Only SQLite's dev
create_all() path was ever creating them, silently masking the gap.

--autogenerate also detected unrelated, pre-existing drift (nullable
changes on 5 billing_configurations columns, plus a dropped index/unique
constraint on invoices/payments/notification_template_states) that
predates and is unrelated to this fix -- deliberately NOT included here;
noted separately for its own investigation rather than bundled into an
unrelated migration.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '73e2ebbe6aad'
down_revision: Union[str, Sequence[str], None] = '7709ed1aee3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('communication_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=255), nullable=True),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.String(length=50), nullable=False),
    sa.Column('event_name', sa.String(length=100), nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=True),
    sa.Column('target_record_id', sa.String(length=255), nullable=True),
    sa.Column('tier', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('suppression_reason', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communication_audit_logs_dedupe_key'), 'communication_audit_logs', ['dedupe_key'], unique=False)
    op.create_index(op.f('ix_communication_audit_logs_event_id'), 'communication_audit_logs', ['event_id'], unique=False)
    op.create_index(op.f('ix_communication_audit_logs_event_name'), 'communication_audit_logs', ['event_name'], unique=False)
    op.create_index(op.f('ix_communication_audit_logs_id'), 'communication_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_communication_audit_logs_organization_id'), 'communication_audit_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_communication_audit_logs_recipient'), 'communication_audit_logs', ['recipient'], unique=False)
    op.create_index(op.f('ix_communication_audit_logs_status'), 'communication_audit_logs', ['status'], unique=False)
    op.create_index(op.f('ix_communication_audit_logs_target_record_id'), 'communication_audit_logs', ['target_record_id'], unique=False)
    op.create_index(op.f('ix_communication_audit_logs_template_id'), 'communication_audit_logs', ['template_id'], unique=False)
    op.create_table('email_marketing_consents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_address', sa.String(length=255), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('has_consented', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_consent_email_org', 'email_marketing_consents', ['email_address', 'organization_id'], unique=False)
    op.create_index(op.f('ix_email_marketing_consents_email_address'), 'email_marketing_consents', ['email_address'], unique=False)
    op.create_index(op.f('ix_email_marketing_consents_id'), 'email_marketing_consents', ['id'], unique=False)
    op.create_index(op.f('ix_email_marketing_consents_organization_id'), 'email_marketing_consents', ['organization_id'], unique=False)
    op.create_table('email_org_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_org_pref_org_cat', 'email_org_preferences', ['organization_id', 'category'], unique=True)
    op.create_index(op.f('ix_email_org_preferences_id'), 'email_org_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_email_org_preferences_organization_id'), 'email_org_preferences', ['organization_id'], unique=False)
    op.create_table('email_suppressions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_address', sa.String(length=255), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('details', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_suppression_email_org', 'email_suppressions', ['email_address', 'organization_id'], unique=False)
    op.create_index(op.f('ix_email_suppressions_email_address'), 'email_suppressions', ['email_address'], unique=False)
    op.create_index(op.f('ix_email_suppressions_id'), 'email_suppressions', ['id'], unique=False)
    op.create_index(op.f('ix_email_suppressions_organization_id'), 'email_suppressions', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_suppressions_organization_id'), table_name='email_suppressions')
    op.drop_index(op.f('ix_email_suppressions_id'), table_name='email_suppressions')
    op.drop_index(op.f('ix_email_suppressions_email_address'), table_name='email_suppressions')
    op.drop_index('idx_suppression_email_org', table_name='email_suppressions')
    op.drop_table('email_suppressions')
    op.drop_index(op.f('ix_email_org_preferences_organization_id'), table_name='email_org_preferences')
    op.drop_index(op.f('ix_email_org_preferences_id'), table_name='email_org_preferences')
    op.drop_index('idx_org_pref_org_cat', table_name='email_org_preferences')
    op.drop_table('email_org_preferences')
    op.drop_index(op.f('ix_email_marketing_consents_organization_id'), table_name='email_marketing_consents')
    op.drop_index(op.f('ix_email_marketing_consents_id'), table_name='email_marketing_consents')
    op.drop_index(op.f('ix_email_marketing_consents_email_address'), table_name='email_marketing_consents')
    op.drop_index('idx_consent_email_org', table_name='email_marketing_consents')
    op.drop_table('email_marketing_consents')
    op.drop_index(op.f('ix_communication_audit_logs_template_id'), table_name='communication_audit_logs')
    op.drop_index(op.f('ix_communication_audit_logs_target_record_id'), table_name='communication_audit_logs')
    op.drop_index(op.f('ix_communication_audit_logs_status'), table_name='communication_audit_logs')
    op.drop_index(op.f('ix_communication_audit_logs_recipient'), table_name='communication_audit_logs')
    op.drop_index(op.f('ix_communication_audit_logs_organization_id'), table_name='communication_audit_logs')
    op.drop_index(op.f('ix_communication_audit_logs_id'), table_name='communication_audit_logs')
    op.drop_index(op.f('ix_communication_audit_logs_event_name'), table_name='communication_audit_logs')
    op.drop_index(op.f('ix_communication_audit_logs_event_id'), table_name='communication_audit_logs')
    op.drop_index(op.f('ix_communication_audit_logs_dedupe_key'), table_name='communication_audit_logs')
    op.drop_table('communication_audit_logs')
    # ### end Alembic commands ###
