"""add public marketing-site assistant tables

Adds the ZB-AI-PUB-001 public (unauthenticated) assistant schema:
  - ai_knowledge_document.is_public flag (only these docs are retrievable by
    the public marketing-site assistant)
  - ai_public_assistant_session / ai_public_assistant_message: anonymous,
    rate-limited chat sessions for the zoikobilling.com widget (deliberately
    independent of ai_conversation which requires org/user FKs)
  - ai_public_rate_limit_counter: per-IP window counters enforced in the
    shared database so the limit holds across every worker process

Revision ID: c3d4e5f6a7b8
Revises: f092a8c6d3e1
Create Date: 2026-09-15

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'c3d4e5f6a7b8'
down_revision: Union[str, Sequence[str], None] = 'f092a8c6d3e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'ai_knowledge_document',
        sa.Column('is_public', sa.Boolean(), server_default='0', nullable=False),
    )
    op.create_index('ix_ai_knowledge_doc_public_status', 'ai_knowledge_document', ['is_public', 'status'], unique=False)

    op.create_table('ai_public_assistant_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_uid', sa.String(length=36), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('message_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_public_assistant_session_id'), 'ai_public_assistant_session', ['id'], unique=False)
    op.create_index(op.f('ix_ai_public_assistant_session_session_uid'), 'ai_public_assistant_session', ['session_uid'], unique=True)

    op.create_table('ai_public_assistant_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_uid', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('sender_type', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', 'TOOL', name='sendertype', native_enum=False), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=True),
    sa.Column('risk_class', sa.Enum('R0', 'R1', 'R2', 'R3', 'R4', 'RX', name='riskclass', native_enum=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['ai_public_assistant_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_public_assistant_message_id'), 'ai_public_assistant_message', ['id'], unique=False)
    op.create_index(op.f('ix_ai_public_assistant_message_message_uid'), 'ai_public_assistant_message', ['message_uid'], unique=True)
    op.create_index(op.f('ix_ai_public_assistant_message_session_id'), 'ai_public_assistant_message', ['session_id'], unique=False)
    op.create_index('ix_ai_public_msg_session_created', 'ai_public_assistant_message', ['session_id', 'created_at'], unique=False)

    op.create_table('ai_public_rate_limit_counter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rate_key', sa.String(length=96), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('count', sa.Integer(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rate_key', 'window_start', name='uq_ai_public_rate_window')
    )
    op.create_index(op.f('ix_ai_public_rate_limit_counter_id'), 'ai_public_rate_limit_counter', ['id'], unique=False)
    op.create_index(op.f('ix_ai_public_rate_limit_counter_rate_key'), 'ai_public_rate_limit_counter', ['rate_key'], unique=False)
    op.create_index(op.f('ix_ai_public_rate_limit_counter_window_start'), 'ai_public_rate_limit_counter', ['window_start'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_public_rate_limit_counter_window_start'), table_name='ai_public_rate_limit_counter')
    op.drop_index(op.f('ix_ai_public_rate_limit_counter_rate_key'), table_name='ai_public_rate_limit_counter')
    op.drop_index(op.f('ix_ai_public_rate_limit_counter_id'), table_name='ai_public_rate_limit_counter')
    op.drop_table('ai_public_rate_limit_counter')

    op.drop_index('ix_ai_public_msg_session_created', table_name='ai_public_assistant_message')
    op.drop_index(op.f('ix_ai_public_assistant_message_session_id'), table_name='ai_public_assistant_message')
    op.drop_index(op.f('ix_ai_public_assistant_message_message_uid'), table_name='ai_public_assistant_message')
    op.drop_index(op.f('ix_ai_public_assistant_message_id'), table_name='ai_public_assistant_message')
    op.drop_table('ai_public_assistant_message')

    op.drop_index(op.f('ix_ai_public_assistant_session_session_uid'), table_name='ai_public_assistant_session')
    op.drop_index(op.f('ix_ai_public_assistant_session_id'), table_name='ai_public_assistant_session')
    op.drop_table('ai_public_assistant_session')

    op.drop_index('ix_ai_knowledge_doc_public_status', table_name='ai_knowledge_document')
    op.drop_column('ai_knowledge_document', 'is_public')
    # ### end Alembic commands ###