"""reconcile models to live schema post-baseline drift

Revision ID: ee85ae4bd5f8
Revises: 8e483f394797
Create Date: 2026-08-31 14:48:41.773925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.core.db_types
import app.modules.commercial.enums

# revision identifiers, used by Alembic.
revision: str = 'ee85ae4bd5f8'
down_revision: Union[str, Sequence[str], None] = '8e483f394797'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entitlement_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('value_type', app.core.db_types.CaseInsensitiveEnum(app.modules.commercial.enums.EntitlementValueType), nullable=False),
    sa.Column('risk_classification', app.core.db_types.CaseInsensitiveEnum(app.modules.commercial.enums.EntitlementRiskClassification), server_default='STANDARD', nullable=False),
    sa.Column('enforcement_type', app.core.db_types.CaseInsensitiveEnum(app.modules.commercial.enums.EntitlementEnforcementType), server_default='HARD', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_globally_disabled', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entitlement_definitions_id'), 'entitlement_definitions', ['id'], unique=False)
    op.create_index(op.f('ix_entitlement_definitions_key'), 'entitlement_definitions', ['key'], unique=True)
    op.create_table('usage_counters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('entitlement_definition_id', sa.Integer(), nullable=False),
    sa.Column('window_key', sa.String(length=32), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('soft_warned_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entitlement_definition_id'], ['entitlement_definitions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'entitlement_definition_id', 'window_key', name='uq_usage_counters_org_def_window')
    )
    op.create_index(op.f('ix_usage_counters_entitlement_definition_id'), 'usage_counters', ['entitlement_definition_id'], unique=False)
    op.create_index(op.f('ix_usage_counters_id'), 'usage_counters', ['id'], unique=False)
    op.create_index(op.f('ix_usage_counters_organization_id'), 'usage_counters', ['organization_id'], unique=False)
    op.create_table('usage_increment_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('entitlement_definition_id', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('window_key', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entitlement_definition_id'], ['entitlement_definitions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'entitlement_definition_id', 'idempotency_key', name='uq_usage_increment_events_dedupe')
    )
    op.create_index(op.f('ix_usage_increment_events_entitlement_definition_id'), 'usage_increment_events', ['entitlement_definition_id'], unique=False)
    op.create_index(op.f('ix_usage_increment_events_id'), 'usage_increment_events', ['id'], unique=False)
    op.create_index(op.f('ix_usage_increment_events_organization_id'), 'usage_increment_events', ['organization_id'], unique=False)
    op.create_table('commercial_evaluation_program_caps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluation_program_id', sa.Integer(), nullable=False),
    sa.Column('entitlement_definition_id', sa.Integer(), nullable=False),
    sa.Column('cap_value', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entitlement_definition_id'], ['entitlement_definitions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['evaluation_program_id'], ['commercial_evaluation_programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evaluation_program_id', 'entitlement_definition_id', name='uq_eval_caps_program_definition')
    )
    op.create_index(op.f('ix_commercial_evaluation_program_caps_entitlement_definition_id'), 'commercial_evaluation_program_caps', ['entitlement_definition_id'], unique=False)
    op.create_index(op.f('ix_commercial_evaluation_program_caps_evaluation_program_id'), 'commercial_evaluation_program_caps', ['evaluation_program_id'], unique=False)
    op.create_index(op.f('ix_commercial_evaluation_program_caps_id'), 'commercial_evaluation_program_caps', ['id'], unique=False)
    op.create_table('commercial_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('entitlement_definition_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', app.core.db_types.CaseInsensitiveEnum(app.modules.commercial.enums.CommercialOverrideStatus), server_default='DRAFT', nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('requested_by_user_id', sa.Integer(), nullable=True),
    sa.Column('approval_request_id', sa.Integer(), nullable=True),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approval_request_id'], ['approval_requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['entitlement_definition_id'], ['entitlement_definitions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['revoked_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commercial_overrides_entitlement_definition_id'), 'commercial_overrides', ['entitlement_definition_id'], unique=False)
    op.create_index(op.f('ix_commercial_overrides_id'), 'commercial_overrides', ['id'], unique=False)
    op.create_index(op.f('ix_commercial_overrides_organization_id'), 'commercial_overrides', ['organization_id'], unique=False)
    op.create_index(op.f('ix_commercial_overrides_status'), 'commercial_overrides', ['status'], unique=False)
    op.create_table('plan_entitlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_version_id', sa.Integer(), nullable=False),
    sa.Column('entitlement_definition_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('is_contracted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entitlement_definition_id'], ['entitlement_definitions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['plan_version_id'], ['commercial_plan_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_version_id', 'entitlement_definition_id', name='uq_plan_entitlements_version_definition')
    )
    op.create_index(op.f('ix_plan_entitlements_entitlement_definition_id'), 'plan_entitlements', ['entitlement_definition_id'], unique=False)
    op.create_index(op.f('ix_plan_entitlements_id'), 'plan_entitlements', ['id'], unique=False)
    op.create_index(op.f('ix_plan_entitlements_plan_version_id'), 'plan_entitlements', ['plan_version_id'], unique=False)
    op.create_table('entitlement_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('commercial_subscription_id', sa.Integer(), nullable=True),
    sa.Column('values', sa.JSON(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.Column('computed_reason', sa.String(length=100), nullable=True),
    sa.Column('snapshot_version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['commercial_subscription_id'], ['commercial_subscriptions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entitlement_snapshots_id'), 'entitlement_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_entitlement_snapshots_organization_id'), 'entitlement_snapshots', ['organization_id'], unique=True)
    op.create_table('subscription_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commercial_subscription_id', sa.Integer(), nullable=False),
    sa.Column('from_plan_id', sa.Integer(), nullable=False),
    sa.Column('to_plan_id', sa.Integer(), nullable=False),
    sa.Column('from_catalog_version_id', sa.Integer(), nullable=True),
    sa.Column('to_catalog_version_id', sa.Integer(), nullable=True),
    sa.Column('direction', app.core.db_types.CaseInsensitiveEnum(app.modules.commercial.enums.SubscriptionChangeDirection), nullable=False),
    sa.Column('status', app.core.db_types.CaseInsensitiveEnum(app.modules.commercial.enums.SubscriptionChangeStatus), server_default='PENDING', nullable=False),
    sa.Column('effective_at', sa.DateTime(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('requested_by_user_id', sa.Integer(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('reversed_at', sa.DateTime(), nullable=True),
    sa.Column('reversed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('blockers', sa.JSON(), nullable=True),
    sa.Column('price_impact', sa.JSON(), nullable=True),
    sa.Column('correlation_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['commercial_subscription_id'], ['commercial_subscriptions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_catalog_version_id'], ['commercial_plan_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['from_plan_id'], ['commercial_plans.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reversed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_catalog_version_id'], ['commercial_plan_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_plan_id'], ['commercial_plans.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_changes_commercial_subscription_id'), 'subscription_changes', ['commercial_subscription_id'], unique=False)
    op.create_index(op.f('ix_subscription_changes_correlation_id'), 'subscription_changes', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_subscription_changes_id'), 'subscription_changes', ['id'], unique=False)
    op.create_index(op.f('ix_subscription_changes_status'), 'subscription_changes', ['status'], unique=False)
    op.create_index('ix_subscription_changes_status_effective_at', 'subscription_changes', ['status', 'effective_at'], unique=False)
    op.add_column('commercial_evaluation_programs', sa.Column('granted_plan_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'commercial_evaluation_programs', 'commercial_plans', ['granted_plan_id'], ['id'], ondelete='RESTRICT')
    op.add_column('commercial_quote_items', sa.Column('entitlement_definition_id', sa.Integer(), nullable=True))
    op.add_column('commercial_quote_items', sa.Column('entitlement_value', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'commercial_quote_items', 'entitlement_definitions', ['entitlement_definition_id'], ['id'], ondelete='RESTRICT')
    op.add_column('commercial_subscriptions', sa.Column('recovery_ends_at', sa.DateTime(), nullable=True))
    op.add_column('commercial_subscriptions', sa.Column('trial_granted_entitlements', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commercial_subscriptions', 'trial_granted_entitlements')
    op.drop_column('commercial_subscriptions', 'recovery_ends_at')
    op.drop_constraint(None, 'commercial_quote_items', type_='foreignkey')
    op.drop_column('commercial_quote_items', 'entitlement_value')
    op.drop_column('commercial_quote_items', 'entitlement_definition_id')
    op.drop_constraint(None, 'commercial_evaluation_programs', type_='foreignkey')
    op.drop_column('commercial_evaluation_programs', 'granted_plan_id')
    op.drop_index('ix_subscription_changes_status_effective_at', table_name='subscription_changes')
    op.drop_index(op.f('ix_subscription_changes_status'), table_name='subscription_changes')
    op.drop_index(op.f('ix_subscription_changes_id'), table_name='subscription_changes')
    op.drop_index(op.f('ix_subscription_changes_correlation_id'), table_name='subscription_changes')
    op.drop_index(op.f('ix_subscription_changes_commercial_subscription_id'), table_name='subscription_changes')
    op.drop_table('subscription_changes')
    op.drop_index(op.f('ix_entitlement_snapshots_organization_id'), table_name='entitlement_snapshots')
    op.drop_index(op.f('ix_entitlement_snapshots_id'), table_name='entitlement_snapshots')
    op.drop_table('entitlement_snapshots')
    op.drop_index(op.f('ix_plan_entitlements_plan_version_id'), table_name='plan_entitlements')
    op.drop_index(op.f('ix_plan_entitlements_id'), table_name='plan_entitlements')
    op.drop_index(op.f('ix_plan_entitlements_entitlement_definition_id'), table_name='plan_entitlements')
    op.drop_table('plan_entitlements')
    op.drop_index(op.f('ix_commercial_overrides_status'), table_name='commercial_overrides')
    op.drop_index(op.f('ix_commercial_overrides_organization_id'), table_name='commercial_overrides')
    op.drop_index(op.f('ix_commercial_overrides_id'), table_name='commercial_overrides')
    op.drop_index(op.f('ix_commercial_overrides_entitlement_definition_id'), table_name='commercial_overrides')
    op.drop_table('commercial_overrides')
    op.drop_index(op.f('ix_commercial_evaluation_program_caps_id'), table_name='commercial_evaluation_program_caps')
    op.drop_index(op.f('ix_commercial_evaluation_program_caps_evaluation_program_id'), table_name='commercial_evaluation_program_caps')
    op.drop_index(op.f('ix_commercial_evaluation_program_caps_entitlement_definition_id'), table_name='commercial_evaluation_program_caps')
    op.drop_table('commercial_evaluation_program_caps')
    op.drop_index(op.f('ix_usage_increment_events_organization_id'), table_name='usage_increment_events')
    op.drop_index(op.f('ix_usage_increment_events_id'), table_name='usage_increment_events')
    op.drop_index(op.f('ix_usage_increment_events_entitlement_definition_id'), table_name='usage_increment_events')
    op.drop_table('usage_increment_events')
    op.drop_index(op.f('ix_usage_counters_organization_id'), table_name='usage_counters')
    op.drop_index(op.f('ix_usage_counters_id'), table_name='usage_counters')
    op.drop_index(op.f('ix_usage_counters_entitlement_definition_id'), table_name='usage_counters')
    op.drop_table('usage_counters')
    op.drop_index(op.f('ix_entitlement_definitions_key'), table_name='entitlement_definitions')
    op.drop_index(op.f('ix_entitlement_definitions_id'), table_name='entitlement_definitions')
    op.drop_table('entitlement_definitions')
    # ### end Alembic commands ###
