"""
email_foundation/registries.py
------------------------------
Event and Template Registries for the Zoiko Billing Email System.

Synchronized with modules/notifications/template_registry.py.
Verbatim template IDs and trigger events sourced from specification.
Activation states are ACTIVE for implemented trigger events in codebase, STUB otherwise.
"""

from dataclasses import dataclass, field
from typing import Dict, List, Optional
from app.services.email_foundation.enums import TemplateTier, ActivationState


@dataclass
class TemplateDefinition:
    id: str
    tier: TemplateTier
    family: str
    required_variables: List[str] = field(default_factory=list)
    activation_state: ActivationState = ActivationState.ACTIVE
    description: str = ""


# Template Registry: ID -> TemplateDefinition
TEMPLATE_REGISTRY: Dict[str, TemplateDefinition] = {
    "ZB-ACQ-001": TemplateDefinition("ZB-ACQ-001", TemplateTier.T3, "ACQ", ['recipient_first_name'], ActivationState.ACTIVE, 'Demo request received'),
    "ZB-ACQ-002": TemplateDefinition("ZB-ACQ-002", TemplateTier.T3, "ACQ", ['recipient_first_name'], ActivationState.STUB, 'Demo scheduled'),
    "ZB-ACQ-003": TemplateDefinition("ZB-ACQ-003", TemplateTier.T3, "ACQ", ['recipient_first_name'], ActivationState.STUB, 'Demo reminder'),
    "ZB-ACQ-004": TemplateDefinition("ZB-ACQ-004", TemplateTier.T3, "ACQ", ['recipient_first_name'], ActivationState.STUB, 'Demo rescheduled or canceled'),
    "ZB-ACQ-005": TemplateDefinition("ZB-ACQ-005", TemplateTier.T3, "ACQ", ['recipient_first_name'], ActivationState.STUB, 'Sales or pricing enquiry received'),
    "ZB-ACQ-006": TemplateDefinition("ZB-ACQ-006", TemplateTier.T4, "ACQ", ['recipient_first_name'], ActivationState.STUB, 'Marketing subscription confirmation'),
    "ZB-CHG-001": TemplateDefinition("ZB-CHG-001", TemplateTier.T1, "CHG", ['recipient_first_name'], ActivationState.ACTIVE, 'Product, service, or catalog item created'),
    "ZB-CHG-002": TemplateDefinition("ZB-CHG-002", TemplateTier.T2, "CHG", ['recipient_first_name'], ActivationState.STUB, 'Product, service, or catalog item changed'),
    "ZB-CHG-003": TemplateDefinition("ZB-CHG-003", TemplateTier.T2, "CHG", ['organization_name', 'recipient_first_name'], ActivationState.STUB, 'Price rule created or changed'),
    "ZB-CHG-004": TemplateDefinition("ZB-CHG-004", TemplateTier.T2, "CHG", ['customer_name', 'recipient_first_name'], ActivationState.STUB, 'Customer-specific pricing changed'),
    "ZB-CHG-005": TemplateDefinition("ZB-CHG-005", TemplateTier.T1, "CHG", ['estimate_number', 'recipient_first_name'], ActivationState.STUB, 'Estimate or quote created'),
    "ZB-CHG-006": TemplateDefinition("ZB-CHG-006", TemplateTier.T1, "CHG", ['quote_number', 'company_name', 'total_amount'], ActivationState.ACTIVE, 'Estimate or quote sent'),
    "ZB-CHG-007": TemplateDefinition("ZB-CHG-007", TemplateTier.T1, "CHG", ['estimate_number', 'recipient_first_name'], ActivationState.ACTIVE, 'Estimate accepted'),
    "ZB-CHG-008": TemplateDefinition("ZB-CHG-008", TemplateTier.T1, "CHG", ['estimate_number', 'recipient_first_name'], ActivationState.STUB, 'Estimate declined or expired'),
    "ZB-CHG-009": TemplateDefinition("ZB-CHG-009", TemplateTier.T1, "CHG", ['charge_reference', 'recipient_first_name'], ActivationState.STUB, 'Charge approval requested'),
    "ZB-CHG-010": TemplateDefinition("ZB-CHG-010", TemplateTier.T1, "CHG", ['charge_reference', 'recipient_first_name'], ActivationState.STUB, 'Charge approved, rejected, or changes requested'),
    "ZB-CHG-011": TemplateDefinition("ZB-CHG-011", TemplateTier.T2, "CHG", ['charge_reference', 'recipient_first_name'], ActivationState.STUB, 'Charge scheduled or ready for billing'),
    "ZB-CHG-012": TemplateDefinition("ZB-CHG-012", TemplateTier.T1, "CHG", ['charge_reference', 'recipient_first_name'], ActivationState.STUB, 'Charge generation or validation failed'),
    "ZB-COL-001": TemplateDefinition("ZB-COL-001", TemplateTier.T2, "COL", ['customer_name', 'overdue_amount', 'currency', 'days_overdue'], ActivationState.ACTIVE, 'Dunning sequence started'),
    "ZB-COL-002": TemplateDefinition("ZB-COL-002", TemplateTier.T2, "COL", ['invoice_number', 'recipient_first_name'], ActivationState.STUB, 'Collections reminder suppressed or placed on hold'),
    "ZB-COL-003": TemplateDefinition("ZB-COL-003", TemplateTier.T1, "COL", ['invoice_number', 'recipient_first_name'], ActivationState.STUB, 'Promise to pay recorded'),
    "ZB-COL-004": TemplateDefinition("ZB-COL-004", TemplateTier.T1, "COL", ['promise_due_date_local', 'recipient_first_name'], ActivationState.STUB, 'Promise-to-pay reminder'),
    "ZB-COL-005": TemplateDefinition("ZB-COL-005", TemplateTier.T1, "COL", ['invoice_number', 'recipient_first_name'], ActivationState.STUB, 'Promise to pay missed'),
    "ZB-COL-006": TemplateDefinition("ZB-COL-006", TemplateTier.T1, "COL", ['organization_name', 'recipient_first_name'], ActivationState.STUB, 'Payment plan created'),
    "ZB-COL-007": TemplateDefinition("ZB-COL-007", TemplateTier.T1, "COL", ['installment_due_date_local', 'recipient_first_name'], ActivationState.STUB, 'Payment-plan installment due'),
    "ZB-COL-008": TemplateDefinition("ZB-COL-008", TemplateTier.T1, "COL", ['recipient_first_name'], ActivationState.STUB, 'Payment-plan installment missed'),
    "ZB-COL-009": TemplateDefinition("ZB-COL-009", TemplateTier.T2, "COL", ['customer_name', 'recipient_first_name'], ActivationState.STUB, 'Collection case escalated'),
    "ZB-COL-010": TemplateDefinition("ZB-COL-010", TemplateTier.T1, "COL", ['customer_name', 'recipient_first_name'], ActivationState.STUB, 'Write-off approval requested'),
    "ZB-COL-011": TemplateDefinition("ZB-COL-011", TemplateTier.T1, "COL", ['customer_name', 'invoice_number', 'written_off_amount'], ActivationState.ACTIVE, 'Write-off decision recorded'),
    "ZB-COL-012": TemplateDefinition("ZB-COL-012", TemplateTier.T1, "COL", ['invoice_number', 'recipient_first_name'], ActivationState.STUB, 'Billing dispute raised or resolved'),
    "ZB-COM-001": TemplateDefinition("ZB-COM-001", TemplateTier.T1, "COM", ['recipient_first_name'], ActivationState.ACTIVE, 'Zoiko Billing account or trial created'),
    "ZB-COM-002": TemplateDefinition("ZB-COM-002", TemplateTier.T3, "COM", ['recipient_first_name'], ActivationState.STUB, 'Trial progress or activation guidance'),
    "ZB-COM-003": TemplateDefinition("ZB-COM-003", TemplateTier.T1, "COM", ['organization_name', 'days_remaining'], ActivationState.ACTIVE, 'Zoiko Billing trial ending'),
    "ZB-COM-004": TemplateDefinition("ZB-COM-004", TemplateTier.T1, "COM", ['organization_name'], ActivationState.ACTIVE, 'Zoiko Billing trial expired'),
    "ZB-COM-005": TemplateDefinition("ZB-COM-005", TemplateTier.T1, "COM", ['recipient_first_name'], ActivationState.ACTIVE, 'Paid Zoiko Billing subscription started'),
    "ZB-COM-006": TemplateDefinition("ZB-COM-006", TemplateTier.T1, "COM", ['recipient_first_name'], ActivationState.ACTIVE, 'Zoiko Billing plan upgraded'),
    "ZB-COM-007": TemplateDefinition("ZB-COM-007", TemplateTier.T1, "COM", ['commercial_subscription_change_effective_date_local', 'recipient_first_name'], ActivationState.ACTIVE, 'Zoiko Billing downgrade scheduled'),
    "ZB-COM-008": TemplateDefinition("ZB-COM-008", TemplateTier.T1, "COM", ['commercial_subscription_renewal_date_local', 'recipient_first_name'], ActivationState.STUB, 'Zoiko Billing renewal upcoming'),
    "ZB-COM-009": TemplateDefinition("ZB-COM-009", TemplateTier.T1, "COM", ['recipient_first_name'], ActivationState.STUB, 'Zoiko Billing subscription payment successful'),
    "ZB-COM-010": TemplateDefinition("ZB-COM-010", TemplateTier.T1, "COM", ['recipient_first_name'], ActivationState.STUB, 'Zoiko Billing subscription payment failed'),
    "ZB-COM-011": TemplateDefinition("ZB-COM-011", TemplateTier.T1, "COM", ['customer_name', 'days_overdue', 'overdue_amount'], ActivationState.ACTIVE, 'Zoiko Billing account past due or suspension warning'),
    "ZB-COM-012": TemplateDefinition("ZB-COM-012", TemplateTier.T1, "COM", ['organization_name', 'recipient_first_name'], ActivationState.ACTIVE, 'Zoiko Billing cancellation, suspension, or reactivation confirmed'),
    "ZB-CUS-001": TemplateDefinition("ZB-CUS-001", TemplateTier.T1, "CUS", ['recipient_first_name'], ActivationState.STUB, 'Customer record created or activated'),
    "ZB-CUS-002": TemplateDefinition("ZB-CUS-002", TemplateTier.T2, "CUS", ['customer_name', 'recipient_first_name'], ActivationState.STUB, 'Customer billing contact added'),
    "ZB-CUS-003": TemplateDefinition("ZB-CUS-003", TemplateTier.T2, "CUS", ['customer_name', 'recipient_first_name'], ActivationState.STUB, 'Customer billing contact changed or removed'),
    "ZB-CUS-004": TemplateDefinition("ZB-CUS-004", TemplateTier.T1, "CUS", ['organization_name', 'recipient_first_name'], ActivationState.STUB, 'Billing portal invitation'),
    "ZB-CUS-005": TemplateDefinition("ZB-CUS-005", TemplateTier.T1, "CUS", ['recipient_first_name'], ActivationState.STUB, 'Billing portal access activated'),
    "ZB-CUS-006": TemplateDefinition("ZB-CUS-006", TemplateTier.T0, "CUS", ['recipient_first_name', 'magic_link_url'], ActivationState.ACTIVE, 'Secure portal sign-in link'),
    "ZB-CUS-007": TemplateDefinition("ZB-CUS-007", TemplateTier.T0, "CUS", ['recipient_first_name'], ActivationState.ACTIVE, 'Portal email or access method changed'),
    "ZB-CUS-008": TemplateDefinition("ZB-CUS-008", TemplateTier.T1, "CUS", ['recipient_first_name'], ActivationState.STUB, 'Portal access revoked'),
    "ZB-GLB-001": TemplateDefinition("ZB-GLB-001", TemplateTier.T2, "GLB", ['invoice_number', 'recipient_first_name'], ActivationState.ACTIVE, 'Electronic invoice submitted'),
    "ZB-GLB-002": TemplateDefinition("ZB-GLB-002", TemplateTier.T1, "GLB", ['invoice_number', 'recipient_first_name'], ActivationState.STUB, 'Electronic invoice accepted or cleared'),
    "ZB-GLB-003": TemplateDefinition("ZB-GLB-003", TemplateTier.T1, "GLB", ['invoice_number', 'recipient_first_name'], ActivationState.STUB, 'Electronic invoice rejected'),
    "ZB-GLB-004": TemplateDefinition("ZB-GLB-004", TemplateTier.T1, "GLB", ['invoice_number', 'recipient_first_name'], ActivationState.STUB, 'Electronic invoice canceled or invalidated'),
    "ZB-GLB-005": TemplateDefinition("ZB-GLB-005", TemplateTier.T2, "GLB", ['invoice_number', 'recipient_first_name'], ActivationState.STUB, 'Electronic-invoicing status delayed'),
    "ZB-GLB-006": TemplateDefinition("ZB-GLB-006", TemplateTier.T1, "GLB", ['customer_name', 'recipient_first_name'], ActivationState.STUB, 'Tax identifier validation failed'),
    "ZB-GLB-007": TemplateDefinition("ZB-GLB-007", TemplateTier.T1, "GLB", ['invoice_number', 'recipient_first_name'], ActivationState.STUB, 'Required jurisdictional information missing'),
    "ZB-GLB-008": TemplateDefinition("ZB-GLB-008", TemplateTier.T1, "GLB", ['recipient_first_name'], ActivationState.STUB, 'Tax calculation or service unavailable'),
    "ZB-GLB-009": TemplateDefinition("ZB-GLB-009", TemplateTier.T1, "GLB", ['invoice_number', 'recipient_first_name'], ActivationState.STUB, 'Withholding document received'),
    "ZB-GLB-010": TemplateDefinition("ZB-GLB-010", TemplateTier.T2, "GLB", ['jurisdiction_name', 'recipient_first_name'], ActivationState.STUB, 'Market or jurisdiction availability changed'),
    "ZB-INT-001": TemplateDefinition("ZB-INT-001", TemplateTier.T2, "INT", ['integration_name', 'recipient_first_name'], ActivationState.ACTIVE, 'Integration connected'),
    "ZB-INT-002": TemplateDefinition("ZB-INT-002", TemplateTier.T1, "INT", ['integration_name', 'recipient_first_name'], ActivationState.STUB, 'Integration disconnected'),
    "ZB-INT-003": TemplateDefinition("ZB-INT-003", TemplateTier.T1, "INT", ['integration_name', 'recipient_first_name'], ActivationState.STUB, 'Integration reauthorization required'),
    "ZB-INT-004": TemplateDefinition("ZB-INT-004", TemplateTier.T2, "INT", ['integration_name', 'recipient_first_name'], ActivationState.ACTIVE, 'Synchronization failed'),
    "ZB-INT-005": TemplateDefinition("ZB-INT-005", TemplateTier.T2, "INT", ['integration_name', 'recipient_first_name'], ActivationState.STUB, 'Synchronization recovered'),
    "ZB-INT-006": TemplateDefinition("ZB-INT-006", TemplateTier.T0, "INT", ['recipient_first_name'], ActivationState.ACTIVE, 'API key created'),
    "ZB-INT-007": TemplateDefinition("ZB-INT-007", TemplateTier.T0, "INT", ['recipient_first_name'], ActivationState.ACTIVE, 'API key rotated'),
    "ZB-INT-008": TemplateDefinition("ZB-INT-008", TemplateTier.T0, "INT", ['recipient_first_name'], ActivationState.ACTIVE, 'API key revoked'),
    "ZB-INT-009": TemplateDefinition("ZB-INT-009", TemplateTier.T1, "INT", ['webhook_endpoint_display', 'recipient_first_name'], ActivationState.STUB, 'Webhook delivery failing'),
    "ZB-INT-010": TemplateDefinition("ZB-INT-010", TemplateTier.T2, "INT", ['recipient_first_name'], ActivationState.STUB, 'Webhook recovered'),
    "ZB-INT-011": TemplateDefinition("ZB-INT-011", TemplateTier.T2, "INT", ['recipient_first_name'], ActivationState.STUB, 'Import completed with exceptions'),
    "ZB-INT-012": TemplateDefinition("ZB-INT-012", TemplateTier.T1, "INT", ['recipient_first_name'], ActivationState.STUB, 'Data export ready'),
    "ZB-INT-013": TemplateDefinition("ZB-INT-013", TemplateTier.T1, "INT", ['recipient_first_name'], ActivationState.STUB, 'Data export failed or expired'),
    "ZB-INT-014": TemplateDefinition("ZB-INT-014", TemplateTier.T2, "INT", ['recipient_first_name'], ActivationState.STUB, 'Sandbox, environment, or endpoint status changed'),
    "ZB-INV-001": TemplateDefinition("ZB-INV-001", TemplateTier.T1, "INV", ['invoice_number', 'recipient_first_name'], ActivationState.ACTIVE, 'Invoice approval requested'),
    "ZB-INV-002": TemplateDefinition("ZB-INV-002", TemplateTier.T1, "INV", ['invoice_number', 'recipient_first_name'], ActivationState.STUB, 'Invoice approved'),
    "ZB-INV-003": TemplateDefinition("ZB-INV-003", TemplateTier.T1, "INV", ['invoice_number', 'recipient_first_name'], ActivationState.ACTIVE, 'Invoice changes requested'),
    "ZB-INV-004": TemplateDefinition("ZB-INV-004", TemplateTier.T1, "INV", ['invoice_number', 'recipient_first_name'], ActivationState.STUB, 'Invoice rejected'),
    "ZB-INV-005": TemplateDefinition("ZB-INV-005", TemplateTier.T2, "INV", ['invoice_number', 'recipient_first_name'], ActivationState.STUB, 'Invoice scheduled'),
    "ZB-INV-006": TemplateDefinition("ZB-INV-006", TemplateTier.T1, "INV", ['invoice_number', 'company_name', 'total_amount'], ActivationState.ACTIVE, 'Invoice issued to customer'),
    "ZB-INV-007": TemplateDefinition("ZB-INV-007", TemplateTier.T2, "INV", ['invoice_number', 'recipient_first_name'], ActivationState.STUB, 'Invoice delivery accepted by mail server'),
    "ZB-INV-008": TemplateDefinition("ZB-INV-008", TemplateTier.T2, "INV", ['invoice_number', 'recipient_first_name'], ActivationState.STUB, 'Invoice delivery delayed or deferred'),
    "ZB-INV-009": TemplateDefinition("ZB-INV-009", TemplateTier.T1, "INV", ['invoice_number', 'recipient_first_name'], ActivationState.STUB, 'Invoice delivery failed'),
    "ZB-INV-010": TemplateDefinition("ZB-INV-010", TemplateTier.T2, "INV", ['customer_name', 'invoice_number', 'recipient_first_name'], ActivationState.STUB, 'Invoice viewed'),
    "ZB-INV-011": TemplateDefinition("ZB-INV-011", TemplateTier.T1, "INV", ['invoice_number', 'due_date', 'days_until_due'], ActivationState.ACTIVE, 'Invoice reminder before due date'),
    "ZB-INV-012": TemplateDefinition("ZB-INV-012", TemplateTier.T1, "INV", ['invoice_number', 'recipient_first_name'], ActivationState.STUB, 'Invoice due today'),
    "ZB-INV-013": TemplateDefinition("ZB-INV-013", TemplateTier.T1, "INV", ['invoice_number', 'company_name'], ActivationState.ACTIVE, 'Invoice overdue reminder'),
    "ZB-INV-014": TemplateDefinition("ZB-INV-014", TemplateTier.T1, "INV", ['invoice_number', 'recipient_first_name'], ActivationState.STUB, 'Partial payment applied'),
    "ZB-INV-015": TemplateDefinition("ZB-INV-015", TemplateTier.T1, "INV", ['invoice_number', 'recipient_first_name'], ActivationState.STUB, 'Invoice paid in full'),
    "ZB-INV-016": TemplateDefinition("ZB-INV-016", TemplateTier.T1, "INV", ['invoice_number', 'recipient_first_name'], ActivationState.STUB, 'Invoice voided'),
    "ZB-INV-017": TemplateDefinition("ZB-INV-017", TemplateTier.T1, "INV", ['invoice_number', 'organization_name', 'recipient_first_name'], ActivationState.STUB, 'Corrected or replacement invoice issued'),
    "ZB-INV-018": TemplateDefinition("ZB-INV-018", TemplateTier.T1, "INV", ['credit_note_number', 'company_name'], ActivationState.ACTIVE, 'Credit note issued'),
    "ZB-INV-019": TemplateDefinition("ZB-INV-019", TemplateTier.T1, "INV", ['debit_note_number', 'organization_name', 'recipient_first_name'], ActivationState.STUB, 'Debit note issued'),
    "ZB-INV-020": TemplateDefinition("ZB-INV-020", TemplateTier.T2, "INV", ['invoice_number', 'recipient_first_name'], ActivationState.STUB, 'Invoice canceled before issue'),
    "ZB-INV-021": TemplateDefinition("ZB-INV-021", TemplateTier.T1, "INV", ['invoice_number', 'recipient_first_name'], ActivationState.STUB, 'Invoice PDF or document generation failed'),
    "ZB-INV-022": TemplateDefinition("ZB-INV-022", TemplateTier.T1, "INV", ['customer_name', 'recipient_first_name'], ActivationState.STUB, 'Recurring invoice generation failed'),
    "ZB-LEG-001": TemplateDefinition("ZB-LEG-001", TemplateTier.T1, "LEG", ['recipient_first_name'], ActivationState.STUB, 'Terms or service agreement update'),
    "ZB-LEG-002": TemplateDefinition("ZB-LEG-002", TemplateTier.T1, "LEG", ['recipient_first_name'], ActivationState.STUB, 'Privacy notice update'),
    "ZB-LEG-003": TemplateDefinition("ZB-LEG-003", TemplateTier.T1, "LEG", ['recipient_first_name'], ActivationState.STUB, 'Privacy or data-subject request received'),
    "ZB-LEG-004": TemplateDefinition("ZB-LEG-004", TemplateTier.T1, "LEG", ['privacy_request_reference', 'recipient_first_name'], ActivationState.STUB, 'Privacy identity verification required'),
    "ZB-LEG-005": TemplateDefinition("ZB-LEG-005", TemplateTier.T1, "LEG", ['privacy_request_reference', 'recipient_first_name'], ActivationState.STUB, 'Privacy request completed or refused'),
    "ZB-LEG-006": TemplateDefinition("ZB-LEG-006", TemplateTier.T1, "LEG", ['organization_name', 'recipient_first_name'], ActivationState.STUB, 'Account or organization deletion requested'),
    "ZB-LEG-007": TemplateDefinition("ZB-LEG-007", TemplateTier.T1, "LEG", ['organization_name', 'recipient_first_name'], ActivationState.STUB, 'Deletion scheduled or completed'),
    "ZB-LEG-008": TemplateDefinition("ZB-LEG-008", TemplateTier.T0, "LEG", ['recipient_first_name'], ActivationState.ACTIVE, 'Security or privacy incident notice'),
    "ZB-MKT-001": TemplateDefinition("ZB-MKT-001", TemplateTier.T4, "MKT", ['recipient_first_name', 'campaign_title'], ActivationState.ACTIVE, 'Activation guidance'),
    "ZB-MKT-002": TemplateDefinition("ZB-MKT-002", TemplateTier.T3, "MKT", ['feature_name', 'recipient_first_name'], ActivationState.STUB, 'Feature education'),
    "ZB-MKT-003": TemplateDefinition("ZB-MKT-003", TemplateTier.T3, "MKT", ['organization_name', 'recipient_first_name'], ActivationState.STUB, 'Usage milestone'),
    "ZB-MKT-004": TemplateDefinition("ZB-MKT-004", TemplateTier.T3, "MKT", ['recipient_first_name'], ActivationState.STUB, 'Inactivity re-engagement'),
    "ZB-MKT-005": TemplateDefinition("ZB-MKT-005", TemplateTier.T4, "MKT", ['release_public_title', 'recipient_first_name'], ActivationState.STUB, 'Product-release announcement'),
    "ZB-MKT-006": TemplateDefinition("ZB-MKT-006", TemplateTier.T4, "MKT", ['event_public_title', 'recipient_first_name'], ActivationState.STUB, 'Webinar or educational event'),
    "ZB-MKT-007": TemplateDefinition("ZB-MKT-007", TemplateTier.T4, "MKT", ['organization_name', 'recipient_first_name'], ActivationState.STUB, 'Contextual plan or capacity recommendation'),
    "ZB-MKT-008": TemplateDefinition("ZB-MKT-008", TemplateTier.T4, "MKT", ['recipient_first_name'], ActivationState.STUB, 'Zoiko One pathway or cross-product education'),
    "ZB-ONB-001": TemplateDefinition("ZB-ONB-001", TemplateTier.T1, "ONB", ['organization_name', 'recipient_first_name'], ActivationState.ACTIVE, 'Product welcome'),
    "ZB-ONB-002": TemplateDefinition("ZB-ONB-002", TemplateTier.T2, "ONB", ['recipient_first_name'], ActivationState.STUB, 'Setup checklist or progress summary'),
    "ZB-ONB-003": TemplateDefinition("ZB-ONB-003", TemplateTier.T2, "ONB", ['organization_name', 'recipient_first_name'], ActivationState.STUB, 'Business profile incomplete'),
    "ZB-ONB-004": TemplateDefinition("ZB-ONB-004", TemplateTier.T2, "ONB", ['organization_name', 'recipient_first_name'], ActivationState.STUB, 'Tax configuration incomplete'),
    "ZB-ONB-005": TemplateDefinition("ZB-ONB-005", TemplateTier.T2, "ONB", ['recipient_first_name'], ActivationState.STUB, 'Invoice numbering requires setup'),
    "ZB-ONB-006": TemplateDefinition("ZB-ONB-006", TemplateTier.T2, "ONB", ['recipient_first_name'], ActivationState.STUB, 'Payment collection setup incomplete'),
    "ZB-ONB-007": TemplateDefinition("ZB-ONB-007", TemplateTier.T2, "ONB", ['recipient_first_name'], ActivationState.STUB, 'Billing sender-domain verification requested'),
    "ZB-ONB-008": TemplateDefinition("ZB-ONB-008", TemplateTier.T2, "ONB", ['sender_domain_name', 'recipient_first_name'], ActivationState.STUB, 'Billing sender domain verified'),
    "ZB-ONB-009": TemplateDefinition("ZB-ONB-009", TemplateTier.T2, "ONB", ['recipient_first_name'], ActivationState.STUB, 'Data import completed'),
    "ZB-ONB-010": TemplateDefinition("ZB-ONB-010", TemplateTier.T2, "ONB", ['recipient_first_name'], ActivationState.STUB, 'Data import failed'),
    "ZB-ONB-011": TemplateDefinition("ZB-ONB-011", TemplateTier.T3, "ONB", ['recipient_first_name', 'organization_name'], ActivationState.ACTIVE, 'First invoice issued'),
    "ZB-ONB-012": TemplateDefinition("ZB-ONB-012", TemplateTier.T3, "ONB", ['organization_name', 'recipient_first_name'], ActivationState.STUB, 'Core onboarding completed'),
    "ZB-OPS-001": TemplateDefinition("ZB-OPS-001", TemplateTier.T0, "OPS", ['alert_title', 'alert_details'], ActivationState.ACTIVE, 'Transactional delivery degradation'),
    "ZB-OPS-002": TemplateDefinition("ZB-OPS-002", TemplateTier.T0, "OPS", ['recipient_first_name'], ActivationState.STUB, 'Complaint or bounce-rate threshold'),
    "ZB-OPS-003": TemplateDefinition("ZB-OPS-003", TemplateTier.T0, "OPS", ['recipient_first_name'], ActivationState.STUB, 'Domain-authentication degradation'),
    "ZB-OPS-004": TemplateDefinition("ZB-OPS-004", TemplateTier.T0, "OPS", ['recipient_first_name'], ActivationState.STUB, 'Payment-provider degradation'),
    "ZB-OPS-005": TemplateDefinition("ZB-OPS-005", TemplateTier.T0, "OPS", ['recipient_first_name'], ActivationState.STUB, 'Invoice-generation backlog'),
    "ZB-OPS-006": TemplateDefinition("ZB-OPS-006", TemplateTier.T0, "OPS", ['recipient_first_name'], ActivationState.STUB, 'Abnormal billing, refund, or export activity'),
    "ZB-OPS-007": TemplateDefinition("ZB-OPS-007", TemplateTier.T1, "OPS", ['recipient_first_name'], ActivationState.ACTIVE, 'Webhook or integration failure concentration'),
    "ZB-OPS-008": TemplateDefinition("ZB-OPS-008", TemplateTier.T1, "OPS", ['recipient_first_name'], ActivationState.STUB, 'Export, report, or batch-processing backlog'),
    "ZB-OPS-009": TemplateDefinition("ZB-OPS-009", TemplateTier.T1, "OPS", ['recipient_first_name'], ActivationState.STUB, 'Electronic-invoicing rejection spike'),
    "ZB-OPS-010": TemplateDefinition("ZB-OPS-010", TemplateTier.T0, "OPS", ['recipient_first_name'], ActivationState.STUB, 'Suppression or consent-system anomaly'),
    "ZB-OPS-011": TemplateDefinition("ZB-OPS-011", TemplateTier.T0, "OPS", ['recipient_first_name'], ActivationState.STUB, 'Communications dead-letter threshold'),
    "ZB-OPS-012": TemplateDefinition("ZB-OPS-012", TemplateTier.T0, "OPS", ['recipient_first_name'], ActivationState.STUB, 'Security, privacy, or legal deadline alert'),
    "ZB-ORG-001": TemplateDefinition("ZB-ORG-001", TemplateTier.T1, "ORG", ['organization_name', 'recipient_first_name'], ActivationState.ACTIVE, 'Organization created'),
    "ZB-ORG-002": TemplateDefinition("ZB-ORG-002", TemplateTier.T1, "ORG", ['organization_name'], ActivationState.ACTIVE, 'Team invitation issued'),
    "ZB-ORG-003": TemplateDefinition("ZB-ORG-003", TemplateTier.T2, "ORG", ['organization_name', 'recipient_first_name'], ActivationState.ACTIVE, 'Team invitation reminder'),
    "ZB-ORG-004": TemplateDefinition("ZB-ORG-004", TemplateTier.T2, "ORG", ['member_full_name', 'organization_name', 'recipient_first_name'], ActivationState.ACTIVE, 'Invitation accepted'),
    "ZB-ORG-005": TemplateDefinition("ZB-ORG-005", TemplateTier.T1, "ORG", ['recipient_first_name'], ActivationState.ACTIVE, 'Invitation expired, revoked, or declined'),
    "ZB-ORG-006": TemplateDefinition("ZB-ORG-006", TemplateTier.T1, "ORG", ['organization_name', 'recipient_first_name'], ActivationState.ACTIVE, 'Role changed'),
    "ZB-ORG-007": TemplateDefinition("ZB-ORG-007", TemplateTier.T1, "ORG", ['organization_name', 'recipient_first_name'], ActivationState.ACTIVE, 'Administrator access assigned'),
    "ZB-ORG-008": TemplateDefinition("ZB-ORG-008", TemplateTier.T1, "ORG", ['organization_name', 'recipient_first_name'], ActivationState.ACTIVE, 'Administrator access removed'),
    "ZB-ORG-009": TemplateDefinition("ZB-ORG-009", TemplateTier.T1, "ORG", ['recipient_first_name'], ActivationState.ACTIVE, 'Ownership transfer requested'),
    "ZB-ORG-010": TemplateDefinition("ZB-ORG-010", TemplateTier.T1, "ORG", ['organization_name', 'recipient_first_name'], ActivationState.ACTIVE, 'Ownership transferred'),
    "ZB-ORG-011": TemplateDefinition("ZB-ORG-011", TemplateTier.T1, "ORG", ['organization_name', 'recipient_first_name'], ActivationState.ACTIVE, 'Member removed'),
    "ZB-ORG-012": TemplateDefinition("ZB-ORG-012", TemplateTier.T1, "ORG", ['organization_name', 'recipient_first_name'], ActivationState.ACTIVE, 'Entity access or entity assignment changed'),
    "ZB-PAY-001": TemplateDefinition("ZB-PAY-001", TemplateTier.T1, "PAY", ['organization_name', 'recipient_first_name'], ActivationState.ACTIVE, 'Payment request issued'),
    "ZB-PAY-002": TemplateDefinition("ZB-PAY-002", TemplateTier.T1, "PAY", ['payment_reference', 'amount', 'company_name'], ActivationState.ACTIVE, 'Payment received — payer confirmation'),
    "ZB-PAY-003": TemplateDefinition("ZB-PAY-003", TemplateTier.T1, "PAY", ['payment_amount_formatted', 'customer_name', 'recipient_first_name'], ActivationState.STUB, 'Payment received — tenant notification'),
    "ZB-PAY-004": TemplateDefinition("ZB-PAY-004", TemplateTier.T1, "PAY", ['recipient_first_name'], ActivationState.STUB, 'Payment pending or processing'),
    "ZB-PAY-005": TemplateDefinition("ZB-PAY-005", TemplateTier.T1, "PAY", ['organization_name', 'recipient_first_name'], ActivationState.STUB, 'Payment failed — payer'),
    "ZB-PAY-006": TemplateDefinition("ZB-PAY-006", TemplateTier.T1, "PAY", ['customer_name', 'recipient_first_name'], ActivationState.STUB, 'Payment failed — tenant'),
    "ZB-PAY-007": TemplateDefinition("ZB-PAY-007", TemplateTier.T1, "PAY", ['payment_next_retry_date_local', 'recipient_first_name'], ActivationState.STUB, 'Automatic payment retry scheduled'),
    "ZB-PAY-008": TemplateDefinition("ZB-PAY-008", TemplateTier.T1, "PAY", ['organization_name', 'recipient_first_name'], ActivationState.STUB, 'Upcoming automatic payment'),
    "ZB-PAY-009": TemplateDefinition("ZB-PAY-009", TemplateTier.T1, "PAY", ['recipient_first_name'], ActivationState.STUB, 'Payment method expiring'),
    "ZB-PAY-010": TemplateDefinition("ZB-PAY-010", TemplateTier.T0, "PAY", ['recipient_first_name'], ActivationState.ACTIVE, 'Payment method added'),
    "ZB-PAY-011": TemplateDefinition("ZB-PAY-011", TemplateTier.T0, "PAY", ['recipient_first_name'], ActivationState.ACTIVE, 'Payment method removed'),
    "ZB-PAY-012": TemplateDefinition("ZB-PAY-012", TemplateTier.T1, "PAY", ['organization_name', 'recipient_first_name'], ActivationState.STUB, 'Refund initiated'),
    "ZB-PAY-013": TemplateDefinition("ZB-PAY-013", TemplateTier.T1, "PAY", ['refund_reference', 'amount', 'company_name'], ActivationState.ACTIVE, 'Refund completed'),
    "ZB-PAY-014": TemplateDefinition("ZB-PAY-014", TemplateTier.T1, "PAY", ['refund_reference', 'recipient_first_name'], ActivationState.STUB, 'Refund failed or action required'),
    "ZB-PAY-015": TemplateDefinition("ZB-PAY-015", TemplateTier.T1, "PAY", ['payment_reference', 'recipient_first_name'], ActivationState.STUB, 'Payment dispute opened'),
    "ZB-PAY-016": TemplateDefinition("ZB-PAY-016", TemplateTier.T1, "PAY", ['dispute_reference', 'recipient_first_name'], ActivationState.STUB, 'Dispute evidence due'),
    "ZB-PAY-017": TemplateDefinition("ZB-PAY-017", TemplateTier.T1, "PAY", ['dispute_reference', 'recipient_first_name'], ActivationState.STUB, 'Payment dispute resolved'),
    "ZB-PAY-018": TemplateDefinition("ZB-PAY-018", TemplateTier.T1, "PAY", ['recipient_first_name'], ActivationState.STUB, 'Unmatched payment recorded'),
    "ZB-PAY-019": TemplateDefinition("ZB-PAY-019", TemplateTier.T1, "PAY", ['payment_reference', 'recipient_first_name'], ActivationState.STUB, 'Payment allocation changed'),
    "ZB-PAY-020": TemplateDefinition("ZB-PAY-020", TemplateTier.T1, "PAY", ['payment_reference', 'recipient_first_name'], ActivationState.STUB, 'Payment reversal or return recorded'),
    "ZB-PAY-021": TemplateDefinition("ZB-PAY-021", TemplateTier.T1, "PAY", ['recipient_first_name'], ActivationState.ACTIVE, 'Reconciliation exception detected'),
    "ZB-PAY-022": TemplateDefinition("ZB-PAY-022", TemplateTier.T2, "PAY", ['recipient_first_name'], ActivationState.ACTIVE, 'Reconciliation completed'),
    "ZB-PRF-001": TemplateDefinition("ZB-PRF-001", TemplateTier.T3, "PRF", ['recipient_first_name'], ActivationState.ACTIVE, 'Marketing subscription confirmed'),
    "ZB-PRF-002": TemplateDefinition("ZB-PRF-002", TemplateTier.T4, "PRF", ['recipient_first_name'], ActivationState.STUB, 'Marketing unsubscribe confirmed'),
    "ZB-PRF-003": TemplateDefinition("ZB-PRF-003", TemplateTier.T1, "PRF", ['recipient_first_name'], ActivationState.STUB, 'Notification preferences changed'),
    "ZB-PRF-004": TemplateDefinition("ZB-PRF-004", TemplateTier.T2, "PRF", ['recipient_first_name'], ActivationState.STUB, 'Digest schedule changed'),
    "ZB-PRF-005": TemplateDefinition("ZB-PRF-005", TemplateTier.T1, "PRF", ['organization_name', 'recipient_first_name'], ActivationState.STUB, 'Tenant sender identity changed or verification degraded'),
    "ZB-PRF-006": TemplateDefinition("ZB-PRF-006", TemplateTier.T1, "PRF", ['recipient_email_masked', 'recipient_first_name'], ActivationState.STUB, 'Recipient suppression or deliverability restriction applied'),
    "ZB-RPT-001": TemplateDefinition("ZB-RPT-001", TemplateTier.T2, "RPT", ['report_name'], ActivationState.ACTIVE, 'Scheduled report ready'),
    "ZB-RPT-002": TemplateDefinition("ZB-RPT-002", TemplateTier.T2, "RPT", ['report_name', 'recipient_first_name'], ActivationState.STUB, 'Scheduled report failed'),
    "ZB-RPT-003": TemplateDefinition("ZB-RPT-003", TemplateTier.T2, "RPT", ['organization_name', 'report_period_display', 'recipient_first_name'], ActivationState.STUB, 'Monthly billing summary'),
    "ZB-RPT-004": TemplateDefinition("ZB-RPT-004", TemplateTier.T2, "RPT", ['report_period_display', 'recipient_first_name'], ActivationState.STUB, 'Receivables aging summary'),
    "ZB-RPT-005": TemplateDefinition("ZB-RPT-005", TemplateTier.T2, "RPT", ['report_period_display', 'recipient_first_name'], ActivationState.STUB, 'Collections performance summary'),
    "ZB-RPT-006": TemplateDefinition("ZB-RPT-006", TemplateTier.T2, "RPT", ['recipient_first_name'], ActivationState.STUB, 'Data quality or exception summary'),
    "ZB-SEC-001": TemplateDefinition("ZB-SEC-001", TemplateTier.T0, "SEC", ['recipient_first_name', 'verify_url'], ActivationState.STUB, 'Verify email address'),
    "ZB-SEC-002": TemplateDefinition("ZB-SEC-002", TemplateTier.T0, "SEC", ['recipient_first_name', 'signin_code'], ActivationState.STUB, 'Email address verified'),
    "ZB-SEC-003": TemplateDefinition("ZB-SEC-003", TemplateTier.T0, "SEC", ['recipient_first_name', 'reset_url'], ActivationState.ACTIVE, 'Sign-in verification code'),
    "ZB-SEC-004": TemplateDefinition("ZB-SEC-004", TemplateTier.T0, "SEC", ['recipient_first_name'], ActivationState.ACTIVE, 'Password reset requested'),
    "ZB-SEC-005": TemplateDefinition("ZB-SEC-005", TemplateTier.T0, "SEC", ['recipient_first_name'], ActivationState.ACTIVE, 'Password changed'),
    "ZB-SEC-006": TemplateDefinition("ZB-SEC-006", TemplateTier.T0, "SEC", ['recipient_first_name'], ActivationState.ACTIVE, 'Multi-factor authentication enabled'),
    "ZB-SEC-007": TemplateDefinition("ZB-SEC-007", TemplateTier.T0, "SEC", ['recipient_first_name'], ActivationState.STUB, 'Multi-factor authentication disabled'),
    "ZB-SEC-008": TemplateDefinition("ZB-SEC-008", TemplateTier.T0, "SEC", ['recipient_first_name'], ActivationState.STUB, 'Recovery codes regenerated'),
    "ZB-SEC-009": TemplateDefinition("ZB-SEC-009", TemplateTier.T0, "SEC", ['recipient_first_name'], ActivationState.STUB, 'New-device sign-in'),
    "ZB-SEC-010": TemplateDefinition("ZB-SEC-010", TemplateTier.T0, "SEC", ['recipient_first_name'], ActivationState.ACTIVE, 'Suspicious sign-in blocked'),
    "ZB-SEC-011": TemplateDefinition("ZB-SEC-011", TemplateTier.T0, "SEC", ['recipient_first_name'], ActivationState.STUB, 'Account temporarily locked'),
    "ZB-SEC-012": TemplateDefinition("ZB-SEC-012", TemplateTier.T0, "SEC", ['recipient_first_name'], ActivationState.STUB, 'Email-address change requested'),
    "ZB-SEC-013": TemplateDefinition("ZB-SEC-013", TemplateTier.T0, "SEC", ['recipient_first_name'], ActivationState.STUB, 'Email address changed'),
    "ZB-SEC-014": TemplateDefinition("ZB-SEC-014", TemplateTier.T0, "SEC", ['recipient_first_name'], ActivationState.STUB, 'Account recovery started'),
    "ZB-SEC-015": TemplateDefinition("ZB-SEC-015", TemplateTier.T0, "SEC", ['recipient_first_name'], ActivationState.STUB, 'Account recovery completed'),
    "ZB-SEC-016": TemplateDefinition("ZB-SEC-016", TemplateTier.T0, "SEC", ['recipient_first_name'], ActivationState.STUB, 'Active session or trusted device revoked'),
    "ZB-SEC-017": TemplateDefinition("ZB-SEC-017", TemplateTier.T0, "SEC", ['recipient_first_name', 'settings_url'], ActivationState.ACTIVE, 'Admin-initiated MFA reset'),
    "ZB-SEC-018": TemplateDefinition("ZB-SEC-018", TemplateTier.T0, "SEC", ['recipient_first_name', 'organization_name', 'reason', 'ticket_reference'], ActivationState.ACTIVE, 'Privileged support access requested'),
    "ZB-SUB-001": TemplateDefinition("ZB-SUB-001", TemplateTier.T1, "SUB", ['subscription_name', 'organization_name', 'recipient_first_name'], ActivationState.ACTIVE, 'Customer subscription created'),
    "ZB-SUB-002": TemplateDefinition("ZB-SUB-002", TemplateTier.T1, "SUB", ['organization_name', 'recipient_first_name'], ActivationState.STUB, 'Customer trial started'),
    "ZB-SUB-003": TemplateDefinition("ZB-SUB-003", TemplateTier.T1, "SUB", ['subscription_name', 'subscription_trial_end_date_local', 'recipient_first_name'], ActivationState.STUB, 'Customer trial ending'),
    "ZB-SUB-004": TemplateDefinition("ZB-SUB-004", TemplateTier.T1, "SUB", ['subscription_name', 'subscription_current_period_end_local', 'recipient_first_name'], ActivationState.STUB, 'Renewal upcoming'),
    "ZB-SUB-005": TemplateDefinition("ZB-SUB-005", TemplateTier.T1, "SUB", ['subscription_number', 'plan_name'], ActivationState.ACTIVE, 'Subscription renewed'),
    "ZB-SUB-006": TemplateDefinition("ZB-SUB-006", TemplateTier.T1, "SUB", ['organization_name', 'recipient_first_name'], ActivationState.STUB, 'Subscription changed'),
    "ZB-SUB-007": TemplateDefinition("ZB-SUB-007", TemplateTier.T1, "SUB", ['organization_name', 'recipient_first_name'], ActivationState.STUB, 'Subscription paused'),
    "ZB-SUB-008": TemplateDefinition("ZB-SUB-008", TemplateTier.T1, "SUB", ['organization_name', 'recipient_first_name'], ActivationState.STUB, 'Subscription resumed'),
    "ZB-SUB-009": TemplateDefinition("ZB-SUB-009", TemplateTier.T1, "SUB", ['subscription_cancellation_date_local', 'recipient_first_name'], ActivationState.STUB, 'Cancellation scheduled'),
    "ZB-SUB-010": TemplateDefinition("ZB-SUB-010", TemplateTier.T1, "SUB", ['organization_name', 'recipient_first_name'], ActivationState.ACTIVE, 'Subscription canceled'),
    "ZB-SUB-011": TemplateDefinition("ZB-SUB-011", TemplateTier.T2, "SUB", ['usage_meter_name', 'usage_threshold_formatted', 'recipient_first_name'], ActivationState.STUB, 'Usage threshold reached'),
    "ZB-SUB-012": TemplateDefinition("ZB-SUB-012", TemplateTier.T1, "SUB", ['recipient_first_name'], ActivationState.STUB, 'Usage data import failed'),
    "ZB-SUB-013": TemplateDefinition("ZB-SUB-013", TemplateTier.T2, "SUB", ['usage_billing_period_display', 'recipient_first_name'], ActivationState.STUB, 'Usage period finalized'),
    "ZB-SUB-014": TemplateDefinition("ZB-SUB-014", TemplateTier.T1, "SUB", ['recipient_first_name'], ActivationState.STUB, 'Recurring billing schedule failed or paused'),
    "ZB-SUP-001": TemplateDefinition("ZB-SUP-001", TemplateTier.T2, "SUP", ['ticket_id'], ActivationState.ACTIVE, 'Support request received'),
    "ZB-SUP-002": TemplateDefinition("ZB-SUP-002", TemplateTier.T1, "SUP", ['support_case_reference', 'recipient_first_name'], ActivationState.STUB, 'Support case updated'),
    "ZB-SUP-003": TemplateDefinition("ZB-SUP-003", TemplateTier.T1, "SUP", ['support_case_reference', 'recipient_first_name'], ActivationState.STUB, 'Support case awaiting customer'),
    "ZB-SUP-004": TemplateDefinition("ZB-SUP-004", TemplateTier.T1, "SUP", ['support_case_reference', 'recipient_first_name'], ActivationState.STUB, 'Support case resolved'),
    "ZB-SUP-005": TemplateDefinition("ZB-SUP-005", TemplateTier.T2, "SUP", ['incident_title'], ActivationState.ACTIVE, 'Service incident started'),
    "ZB-SUP-006": TemplateDefinition("ZB-SUP-006", TemplateTier.T1, "SUP", ['incident_public_title', 'recipient_first_name'], ActivationState.STUB, 'Service incident update'),
    "ZB-SUP-007": TemplateDefinition("ZB-SUP-007", TemplateTier.T1, "SUP", ['incident_public_title', 'recipient_first_name'], ActivationState.STUB, 'Service incident resolved'),
    "ZB-SUP-008": TemplateDefinition("ZB-SUP-008", TemplateTier.T2, "SUP", ['maintenance_start_date_local', 'recipient_first_name'], ActivationState.STUB, 'Scheduled maintenance announced, updated, or completed'),
    "ZB-GAP-001": TemplateDefinition("ZB-GAP-001", TemplateTier.T1, "GAP", ['subscription_number'], ActivationState.ACTIVE, 'Tenant subscription cancelled notification (legacy alias -> ZB-COM-012)'),
    "ZB-GAP-002": TemplateDefinition("ZB-GAP-002", TemplateTier.T1, "GAP", ['invoice_number', 'customer_name'], ActivationState.ACTIVE, 'Customer invoice voided notification (legacy alias -> ZB-INV-003)'),
    "ZB-GAP-003": TemplateDefinition("ZB-GAP-003", TemplateTier.T1, "GAP", ['organization_name', 'plan_name'], ActivationState.ACTIVE, 'Commercial platform plan changed notification (legacy alias -> ZB-COM-006)'),
    "ZB-GAP-004": TemplateDefinition("ZB-GAP-004", TemplateTier.T1, "GAP", ['plan_name'], ActivationState.ACTIVE, 'Commercial plan version published digest (legacy alias -> ZB-MKT-005)'),
    "ZB-GAP-005": TemplateDefinition("ZB-GAP-005", TemplateTier.T1, "GAP", ['recipient_first_name'], ActivationState.ACTIVE, 'Entitlement override decided notification (legacy alias -> ZB-ORG-012)'),
    "ZB-GAP-006": TemplateDefinition("ZB-GAP-006", TemplateTier.T0, "GAP", ['organization_name'], ActivationState.ACTIVE, 'Organization lifecycle changed notification (legacy alias -> ZB-ORG-001)'),
    "ZB-GAP-007": TemplateDefinition("ZB-GAP-007", TemplateTier.T1, "GAP", ['recipient_first_name', 'organization_name'], ActivationState.ACTIVE, 'User role changed notification (legacy alias -> ZB-ORG-006)'),
    "ZB-GAP-008": TemplateDefinition("ZB-GAP-008", TemplateTier.T0, "GAP", ['recipient_first_name', 'organization_name'], ActivationState.ACTIVE, 'User status changed notification (legacy alias -> ZB-ORG-011)'),
    "ZB-GAP-009": TemplateDefinition("ZB-GAP-009", TemplateTier.T0, "GAP", ['recipient_first_name', 'organization_name'], ActivationState.ACTIVE, 'Privileged access session ended (legacy alias -> ZB-ORG-008)'),
    "ZB-COM-014": TemplateDefinition("ZB-COM-014", TemplateTier.T1, "COM", ['organization_name'], ActivationState.ACTIVE, 'Recovery window expired notification (legacy alias -> ZB-COM-012)'),
    "ZB-COM-015": TemplateDefinition("ZB-COM-015", TemplateTier.T1, "COM", ['organization_name', 'plan_name'], ActivationState.ACTIVE, 'Trial to paid conversion confirmation (legacy alias -> ZB-COM-005)'),
    "ZB-GEN-000": TemplateDefinition("ZB-GEN-000", TemplateTier.T1, "GEN", [], ActivationState.ACTIVE, 'Generic fallback notification template'),
}

# Event Registry: Event Name -> List[Template ID]
EVENT_REGISTRY: Dict[str, List[str]] = {
    'api_key.created': ['ZB-INT-006'],
    'api_key.revoked': ['ZB-INT-008'],
    'api_key.rotated': ['ZB-INT-007'],
    'billing_dispute.status_changed': ['ZB-COL-012'],
    'billing_schedule.failed': ['ZB-SUB-014'],
    'catalog.item_changed': ['ZB-CHG-002'],
    'catalog.item_created': ['ZB-CHG-001'],
    'charge.approval_decided': ['ZB-CHG-010'],
    'charge.approval_requested': ['ZB-CHG-009'],
    'charge.failed': ['ZB-CHG-012'],
    'charge.ready_for_billing': ['ZB-CHG-011'],
    'collections.case_escalated': ['ZB-COL-009'],
    'collections.communication_hold': ['ZB-COL-002'],
    'collections.installment_due': ['ZB-COL-007'],
    'collections.installment_missed': ['ZB-COL-008'],
    'collections.payment_plan_created': ['ZB-COL-006'],
    'collections.promise_due': ['ZB-COL-004'],
    'collections.promise_missed': ['ZB-COL-005'],
    'collections.promise_recorded': ['ZB-COL-003'],
    'collections.workflow_started': ['ZB-COL-001'],
    'collections.writeoff_approval_requested': ['ZB-COL-010'],
    'collections.writeoff_decided': ['ZB-COL-011'],
    'commercial_account.created': ['ZB-COM-001'],
    'commercial_account.trial_ending': ['ZB-COM-003'],
    'commercial_account.trial_expired': ['ZB-COM-004'],
    'commercial_account.trial_progress': ['ZB-COM-002'],
    'commercial_subscription.downgrade_scheduled': ['ZB-COM-007'],
    'commercial_subscription.past_due': ['ZB-COM-011'],
    'commercial_subscription.payment_failed': ['ZB-COM-010'],
    'commercial_subscription.payment_succeeded': ['ZB-COM-009'],
    'commercial_subscription.renewal_upcoming': ['ZB-COM-008'],
    'commercial_subscription.started': ['ZB-COM-005'],
    'commercial_subscription.status_changed': ['ZB-COM-012'],
    'commercial_subscription.upgraded': ['ZB-COM-006'],
    'consent.marketing_confirmation_requested': ['ZB-ACQ-006'],
    'credit_note.issued': ['ZB-INV-018'],
    'customer.contact_added': ['ZB-CUS-002'],
    'customer.contact_changed': ['ZB-CUS-003'],
    'customer.created': ['ZB-CUS-001'],
    'data_deletion.requested': ['ZB-LEG-006'],
    'data_deletion.status_changed': ['ZB-LEG-007'],
    'debit_note.issued': ['ZB-INV-019'],
    'developer_environment.status_changed': ['ZB-INT-014'],
    'einvoice.accepted': ['ZB-GLB-002'],
    'einvoice.canceled': ['ZB-GLB-004'],
    'einvoice.rejected': ['ZB-GLB-003'],
    'einvoice.status_delayed': ['ZB-GLB-005'],
    'einvoice.submitted': ['ZB-GLB-001'],
    'entity.membership_changed': ['ZB-ORG-012'],
    'estimate.accepted': ['ZB-CHG-007'],
    'estimate.created': ['ZB-CHG-005'],
    'estimate.ended': ['ZB-CHG-008'],
    'estimate.issued': ['ZB-CHG-006'],
    'export.ready': ['ZB-INT-012'],
    'export.unavailable': ['ZB-INT-013'],
    'identity.account_locked': ['ZB-SEC-011'],
    'identity.email_change_requested': ['ZB-SEC-012'],
    'identity.email_changed': ['ZB-SEC-013'],
    'identity.email_verification_requested': ['ZB-SEC-001'],
    'identity.email_verified': ['ZB-SEC-002'],
    'identity.mfa_disabled': ['ZB-SEC-007'],
    'identity.mfa_enabled': ['ZB-SEC-006'],
    'identity.mfa_reset_by_admin': ['ZB-SEC-017'],
    'identity.new_device_signin': ['ZB-SEC-009'],
    'identity.password_changed': ['ZB-SEC-005'],
    'identity.password_reset_requested': ['ZB-SEC-004'],
    'identity.recovery_codes_regenerated': ['ZB-SEC-008'],
    'identity.recovery_completed': ['ZB-SEC-015'],
    'identity.recovery_started': ['ZB-SEC-014'],
    'identity.risky_signin_blocked': ['ZB-SEC-010'],
    'identity.session_revoked': ['ZB-SEC-016'],
    'identity.signin_code_issued': ['ZB-SEC-003'],
    'import.completed': ['ZB-ONB-009'],
    'import.completed_with_exceptions': ['ZB-INT-011'],
    'import.failed': ['ZB-ONB-010'],
    'integration.connected': ['ZB-INT-001'],
    'integration.disconnected': ['ZB-INT-002'],
    'integration.reauthorization_required': ['ZB-INT-003'],
    'integration.sync_failed': ['ZB-INT-004'],
    'integration.sync_recovered': ['ZB-INT-005'],
    'invoice.approval_requested': ['ZB-INV-001'],
    'invoice.approved': ['ZB-INV-002'],
    'invoice.changes_requested': ['ZB-INV-003'],
    'invoice.delivery_accepted': ['ZB-INV-007'],
    'invoice.delivery_deferred': ['ZB-INV-008'],
    'invoice.delivery_failed': ['ZB-INV-009'],
    'invoice.document_generation_failed': ['ZB-INV-021'],
    'invoice.draft_canceled': ['ZB-INV-020'],
    'invoice.due_today': ['ZB-INV-012'],
    'invoice.issued': ['ZB-INV-006'],
    'invoice.overdue_reminder': ['ZB-INV-013'],
    'invoice.paid': ['ZB-INV-015'],
    'invoice.partially_paid': ['ZB-INV-014'],
    'invoice.pre_due_reminder': ['ZB-INV-011'],
    'invoice.recurring_generation_failed': ['ZB-INV-022'],
    'invoice.rejected': ['ZB-INV-004'],
    'invoice.replaced': ['ZB-INV-017'],
    'invoice.scheduled': ['ZB-INV-005'],
    'invoice.viewed': ['ZB-INV-010'],
    'invoice.voided': ['ZB-INV-016'],
    'jurisdiction.required_fields_missing': ['ZB-GLB-007'],
    'legal.terms_updated': ['ZB-LEG-001'],
    'lifecycle.activation_guidance': ['ZB-MKT-001'],
    'lifecycle.feature_education': ['ZB-MKT-002'],
    'lifecycle.reengagement': ['ZB-MKT-004'],
    'lifecycle.usage_milestone': ['ZB-MKT-003'],
    'market.availability_changed': ['ZB-GLB-010'],
    'marketing.event_invitation': ['ZB-MKT-006'],
    'marketing.plan_recommendation': ['ZB-MKT-007'],
    'marketing.product_release': ['ZB-MKT-005'],
    'marketing.zoiko_one_pathway': ['ZB-MKT-008'],
    'membership.admin_assigned': ['ZB-ORG-007'],
    'membership.admin_removed': ['ZB-ORG-008'],
    'membership.invitation_accepted': ['ZB-ORG-004'],
    'membership.invitation_created': ['ZB-ORG-002'],
    'membership.invitation_ended': ['ZB-ORG-005'],
    'membership.invitation_reminder': ['ZB-ORG-003'],
    'membership.removed': ['ZB-ORG-011'],
    'membership.role_changed': ['ZB-ORG-006'],
    'onboarding.business_profile_incomplete': ['ZB-ONB-003'],
    'onboarding.completed': ['ZB-ONB-012'],
    'onboarding.first_invoice_issued': ['ZB-ONB-011'],
    'onboarding.invoice_numbering_incomplete': ['ZB-ONB-005'],
    'onboarding.payment_setup_incomplete': ['ZB-ONB-006'],
    'onboarding.progress': ['ZB-ONB-002'],
    'onboarding.started': ['ZB-ONB-001'],
    'onboarding.tax_configuration_incomplete': ['ZB-ONB-004'],
    'ops.data_backlog': ['ZB-OPS-008'],
    'ops.dead_letter_threshold': ['ZB-OPS-011'],
    'ops.delivery_degradation': ['ZB-OPS-001'],
    'ops.domain_auth_degradation': ['ZB-OPS-003'],
    'ops.einvoice_rejection_spike': ['ZB-OPS-009'],
    'ops.integration_concentration': ['ZB-OPS-007'],
    'ops.invoice_backlog': ['ZB-OPS-005'],
    'ops.payment_provider_degradation': ['ZB-OPS-004'],
    'ops.regulatory_deadline': ['ZB-OPS-012'],
    'ops.reputation_threshold': ['ZB-OPS-002'],
    'ops.suppression_anomaly': ['ZB-OPS-010'],
    'organization.created': ['ZB-ORG-001'],
    'organization.ownership_transfer_requested': ['ZB-ORG-009'],
    'organization.ownership_transferred': ['ZB-ORG-010'],
    'payment.completed_payer': ['ZB-PAY-002'],
    'payment.completed_tenant': ['ZB-PAY-003'],
    'payment.failed_payer': ['ZB-PAY-005'],
    'payment.failed_tenant': ['ZB-PAY-006'],
    'payment.pending': ['ZB-PAY-004'],
    'payment.request_issued': ['ZB-PAY-001'],
    'payment.retry_scheduled': ['ZB-PAY-007'],
    'payment.reversed': ['ZB-PAY-020'],
    'payment.upcoming': ['ZB-PAY-008'],
    'payment_dispute.evidence_due': ['ZB-PAY-016'],
    'payment_dispute.opened': ['ZB-PAY-015'],
    'payment_dispute.resolved': ['ZB-PAY-017'],
    'payment_method.added': ['ZB-PAY-010'],
    'payment_method.expiring': ['ZB-PAY-009'],
    'payment_method.removed': ['ZB-PAY-011'],
    'portal.access_activated': ['ZB-CUS-005'],
    'portal.access_changed': ['ZB-CUS-007'],
    'portal.access_revoked': ['ZB-CUS-008'],
    'portal.invitation_created': ['ZB-CUS-004'],
    'portal.magic_link_issued': ['ZB-CUS-006'],
    'preference.digest_changed': ['ZB-PRF-004'],
    'preference.marketing_subscribed': ['ZB-PRF-001'],
    'preference.marketing_unsubscribed': ['ZB-PRF-002'],
    'preference.notifications_changed': ['ZB-PRF-003'],
    'pricing.customer_rule_changed': ['ZB-CHG-004'],
    'pricing.rule_changed': ['ZB-CHG-003'],
    'privacy.notice_updated': ['ZB-LEG-002'],
    'privacy.request_completed': ['ZB-LEG-005'],
    'privacy.request_received': ['ZB-LEG-003'],
    'privacy.verification_required': ['ZB-LEG-004'],
    'privacy_incident.notice_approved': ['ZB-LEG-008'],
    'privileged_access.requested': ['ZB-SEC-018'],
    'recipient.delivery_restricted': ['ZB-PRF-006'],
    'reconciliation.allocation_changed': ['ZB-PAY-019'],
    'reconciliation.completed': ['ZB-PAY-022'],
    'reconciliation.exception_detected': ['ZB-PAY-021'],
    'reconciliation.payment_unmatched': ['ZB-PAY-018'],
    'refund.completed': ['ZB-PAY-013'],
    'refund.failed': ['ZB-PAY-014'],
    'refund.initiated': ['ZB-PAY-012'],
    'report.aging_summary': ['ZB-RPT-004'],
    'report.collections_summary': ['ZB-RPT-005'],
    'report.data_quality_summary': ['ZB-RPT-006'],
    'report.failed': ['ZB-RPT-002'],
    'report.monthly_billing_summary': ['ZB-RPT-003'],
    'report.ready': ['ZB-RPT-001'],
    'risk.billing_anomaly': ['ZB-OPS-006'],
    'sales.demo_changed': ['ZB-ACQ-004'],
    'sales.demo_reminder': ['ZB-ACQ-003'],
    'sales.demo_scheduled': ['ZB-ACQ-002'],
    'sender_domain.verification_started': ['ZB-ONB-007'],
    'sender_domain.verified': ['ZB-ONB-008'],
    'sender_identity.status_changed': ['ZB-PRF-005'],
    'status.incident_resolved': ['ZB-SUP-007'],
    'status.incident_started': ['ZB-SUP-005'],
    'status.incident_updated': ['ZB-SUP-006'],
    'status.maintenance_changed': ['ZB-SUP-008'],
    'subscription.canceled': ['ZB-SUB-010'],
    'subscription.cancellation_scheduled': ['ZB-SUB-009'],
    'subscription.changed': ['ZB-SUB-006'],
    'subscription.created': ['ZB-SUB-001'],
    'subscription.paused': ['ZB-SUB-007'],
    'subscription.renewal_upcoming': ['ZB-SUB-004'],
    'subscription.renewed': ['ZB-SUB-005'],
    'subscription.resumed': ['ZB-SUB-008'],
    'subscription.trial_ending': ['ZB-SUB-003'],
    'subscription.trial_started': ['ZB-SUB-002'],
    'support.awaiting_customer': ['ZB-SUP-003'],
    'support.case_created': ['ZB-SUP-001'],
    'support.case_resolved': ['ZB-SUP-004'],
    'support.case_updated': ['ZB-SUP-002'],
    'tax.identifier_validation_failed': ['ZB-GLB-006'],
    'tax.service_unavailable': ['ZB-GLB-008'],
    'usage.import_failed': ['ZB-SUB-012'],
    'usage.period_finalized': ['ZB-SUB-013'],
    'usage.threshold_reached': ['ZB-SUB-011'],
    'web.demo_requested': ['ZB-ACQ-001'],
    'web.sales_enquiry_received': ['ZB-ACQ-005'],
    'webhook.delivery_failing': ['ZB-INT-009'],
    'webhook.recovered': ['ZB-INT-010'],
    'withholding.document_received': ['ZB-GLB-009'],
}

def get_template_definition(template_id: str) -> Optional[TemplateDefinition]:
    """Retrieves a template definition from the registry by ID."""
    return TEMPLATE_REGISTRY.get(template_id)

def get_template_for_event(event_name: str) -> Optional[TemplateDefinition]:
    """Retrieves the primary active template definition for a trigger event."""
    template_ids = EVENT_REGISTRY.get(event_name, [])
    for tid in template_ids:
        defn = TEMPLATE_REGISTRY.get(tid)
        if defn and defn.activation_state == ActivationState.ACTIVE:
            return defn
    for tid in template_ids:
        defn = TEMPLATE_REGISTRY.get(tid)
        if defn:
            return defn
    return None

def get_templates_by_family(family: str) -> List[TemplateDefinition]:
    """Returns all template definitions belonging to a specific family."""
    return [t for t in TEMPLATE_REGISTRY.values() if t.family == family]

def get_templates_by_tier(tier: TemplateTier) -> List[TemplateDefinition]:
    """Returns all template definitions belonging to a specific tier."""
    return [t for t in TEMPLATE_REGISTRY.values() if t.tier == tier]

def get_active_templates() -> List[TemplateDefinition]:
    """Returns all currently active template definitions."""
    return [t for t in TEMPLATE_REGISTRY.values() if t.activation_state == ActivationState.ACTIVE]

